[project]
name = "hardware"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Matias Ceau", email = "matias@ceau.net" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
hardware = "hardware:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
